version: "3.7"

services: # 하나로 묶어주는 서비스를 만듬
  nginx:    # nginx 컨테이너 부분
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_4ban_network

    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_4ban_static:/data/static/
      - gis_4ban_media:/data/media/

  django:   # django 부분
    image: gis_4ban_django:3
    networks:
      - gis_4ban_network

    volumes:
    - gis_4ban_static:/home/lol2/staticfiles/
    - gis_4ban_media:/home/lol2/media/


# 네트워크 생성
networks:
  gis_4ban_network:

# 볼륨 설정
volumes:
  gis_4ban_static:
  gis_4ban_media: